--1, what is the total revenue generated by male vs female  customers
select gender , SUM(purchase_amount) as revenue
from customer 
group by gender

--2, which customrs used aa discount but still spent more than the averaage purchasae amaount 

select  customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3  which is the top  5 products with the highst average review rating ?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--4 campare the aaverage purchaase amoumnt between staaandard aand express shipping

select shipping_type,
ROUND(avg(purchase_amount),2)
from customer 
where shipping_type in('Standard','Express')
Group by shipping_type

--5 do subscribed customers spend more? compare average spend and total revenue betewwn subscribers and non subscriber

sELECT  subscription_status,
COUNT(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue , avg_spend desc

--6 which   5 producst  have the highest  precentage of  purchaases   whch discounts aapplied?

select item_purchased,
round(100  * sum(case when discount_applied = 'Yes' THEN 1 else 0 END)/count(*) ,2) as discount_rate
from customer 
group by item_purchased
order by  discount_rate desc
limit 5

--7. segment customers into new, returning, and loyal based on their total number of previous purchases and show the count  of each segment.
with customer_type as (
select customer_id, previous_purchases,
case  
	when previous_purchases = 1 Then 'new'
	when previous_purchases BETWEEN  2 AND 10 then 'returning'
	ELSE 'loyal'
	END AS customer_segment
from customer  
)

select customer_segment, count(*)  as  "number  of customers"
from customer_type 
group by customer_segment

--8, what are the top 3 most purchased products within each category
	
with item_count as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category  order by count(customer_id) desc) as item_rank
from customer 
group by category , item_purchased
)

select item_rank,  category , item_purchased 
from item_count
where item_rank <= 3;

--9 are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT Subscription_status,
count(customer_id) as repeated_customers
from customer  
where previous_purchases > 5
group by  subscription_status

--10 what is the revenue contribuition  of each age group

select age_group,
sum(purchase_amount) as total_revenue
from customer 
group  by age_group
order by total_revenue desc


